if [ $# -ne 1 ];
then
	echo "usage: $0 token_id"
fi

TOKEN=$1

curl -i http://localhost:8080/api/picture/search -X POST -d '' -H "x-auth-token:$TOKEN" -H "Accept:application/json" -H "Content-Type: application/json" -d "{"pictureFile":"iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAABGdBTUEAALGOfPtRkwAAACBjSFJNAAB6JQAAgIMAAPn/AACA6AAAdTAAAOpgAAA6lwAAF2+XqZnUAAAARVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeYafpAAAAFnRSTlMABAgLDxMXGh4iJiktMTU4PIKrsuPsF0UrNwAAALFJREFUeNrt2EsOgjAUQNFXcAF+ovtfH1HDCtCJ4EBDmNDn59xRw6QnoWkeREiSJEmSJCVXptWx1Ny3GxfNG0rVmuxXAAAAkA7YzN1SEae1nnkFAAAAnwMoM5dU5ZnQGQAA+JGJaLgOj9WhTZmIzuP+cXEGAAD+FLCfVjsTkUMIALDaRLQ0/4gAAAC+BGAiAgAAAAAAAEjvOZBsq+7bv34b3rI/TgEAAAAAAJIAbUhK7g4hCiW8e20fdwAAAABJRU5ErkJggg==", "maxHits":10, "featureDescriptor":"CEDD"}"
